# Generated by Django 3.0.4 on 2020-03-29 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uptade_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uptade_at',
            new_name='update_at',
        ),
    ]
