# Generated by Django 3.0.4 on 2020-04-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
