# Generated by Django 3.0.4 on 2020-05-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_ili'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metrekare',
            field=models.IntegerField(default=10, max_length=50),
        ),
    ]
