# Generated by Django 3.0.4 on 2020-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_metrekare'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='binayasi',
            field=models.IntegerField(default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='isitma',
            field=models.CharField(default='yok', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='kati',
            field=models.IntegerField(default=1, max_length=250),
        ),
    ]
