# Generated by Django 3.0.4 on 2020-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200526_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depozito',
            field=models.IntegerField(default=0, max_length=250),
        ),
    ]
